name: 🦟 Bug
description: File a bug report
title: '[Bug]: '
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the error or unexpected behavior you encountered.
      placeholder: <Description>
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the expected behaviour?
      description: Describe how you expected it to behave.
      placeholder: <Description>
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps needed to trigger the bug.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Screenshots and additional context
      description: Add screenshots and any other context that helps.
      placeholder: Paste or drag screenshots here.
