services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - '${PORT:-3500}:3000'
    environment:
      APP_ENV: production
      NODE_ENV: production
    profiles:
      - production

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '${PORT:-3500}:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      APP_ENV: development
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:3001/api}
    profiles:
      - dev
